=== InnoTep/FGCS2022/Data structures/JSON/service_schema_base.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://example.com/schemas/service",
  "title": "Service",
  "description": "JSON schema of an existing service in the Assisted Smart Home",
  "type": "object",
  "properties": {
		"name": {"type": "string"},
		"description": {"type": "string"},
		"input": {"type": "array",
				  "items": {"$ref": "#/definitions/param"}
		},
		"output": {"type": "array",
				  "items": {"$ref": "#/definitions/param"}
		},
		"exceptions": {"type": "array",
					   "items": {"$ref": "#/definitions/exception"}
		},
		"databases": {"type": "array",
						"items": {
							"type": "string",
							"uniqueItems": true
					    }
		}
	},
	"required": ["name", "description"],
	"additionalProperties":true,
	"definitions":{
		"param": {"type": "object",
				  "properties": {
					  "name": {"type": "string"},
					  "description": {"type": "string"}
				  },
				  "required": ["name", "description"],
				  "additionalProperties":true
		},
		"exception": {"type": "object",
					  "properties": {
						  "name": {"type": "string"},
						  "description": {"type": "string"}
					  },
					  "required": ["name", "description"],
				      "additionalProperties":true
		}
	}
}

=== InnoTep/FGCS2022/Data structures/JSON/Team1/remove_events.json
{
		"name": "Event Removal",
		"description": "The event removal service allows to eliminate those data records that are of no interest and which satisfy particular conditions.",
		"input": [ 
			{
				"name": "remove",
				"description": "List of comma-separated values, either regular expressions or numerical conditions."
			}
		],
		"output": [ 
			{
				"name": "csv",
				"description": "CSV without the selected events."
			}
		],
		"databases": ["Events"]
}

=== InnoTep/FGCS2022/Data structures/JSON/Team1/event_selection.json
{
		"name": "Event Selection",
		"description": "This service allows to select a subset of events from the event database based on a start and finish timestamps and the activity of interest. It must be mentioned that the output CSV has as columns the list of unique attributesidentified across the schemas of the group of sensors associated to thegroup of events selected. If a final column is not present in a specific data recordits value is left as an empty string. Additionally, events are ordered according to the value of the timestamp field, which is common to all data records.",
		"input": [ 
			{
				"name": "start",
				"description": "Timestamp, in ISO 8601 format, indicating the beginning point, inclusive, from which events are selected."
			},{
				"name": "end",
				"description": "Timestamp, in ISO 8601 format, indicating the ending point, inclusive, till which events are selected."
			},{
				"name": "activity",
				"description": "The id or name of the activity which wants to be filtered"
			}
		],
		"output": [ 
			{
				"name": "csv",
				"description": "Output CSV containing the selected events."
			}
		],
		"databases": ["Events"]
}

=== InnoTep/FGCS2022/Data structures/JSON/trace-delimiter.json
{
	"name": "Trace delimiter",
	"description": "Groups events by traces an outputs a conforming event log",
	"input": [
		{"name": "collection_input",
		 "description": "Name of the collection that will be used to feed the service"},
		{"name": "first",
		 "description": "The value of the start activity of a trace"},
		{"name": "last",
		 "description": "The value of the last activity of a trace"},
		{"name": "mask" ,
		 "description": "The topic mask to group same originator events"},
		{"name": "collection_output",
		 "description": "Name of the collection were the resulting records will be stored"}
	],
	"output": [
		{"name": "json",
		 "description": "JSON conforming to the JXES Event Log standard"}
	],
	"databases": ["Event_Log", "Schemas"]
}

=== InnoTep/FGCS2022/Data structures/JSON/Team1/event_grouping.json
{
		"name": "Event Grouping",
		"description": " The event grouping service is in charge of reducing the dimensionality of events by generating higher levels of abstraction for particular actions. It is important to note down that groups must be ordered by increasing size of granularity, as once an event is grouped within one category or action, no other grouping can be applied.",
		"input": [ 
			{
				"name": "init",
				"description": "List of comma-separated values indicating the corresponding start event for each group."
			},{
				"name": "end",
				"description": "List of comma-separated values indicating the corresponding end event for each group."
			},{
				"name": "name",
				"description": "List of comma-separated values indicating the resulting name of the collection of events for each group."
			}
		],
		"output": [ 
			{
				"name": "csv",
				"description": "CSV including the grouped events."
			}
		],
		"databases": ["Events"]
}

=== InnoTep/FGCS2022/Data structures/JSON/Team1/column_standardization.json
{
		"name": "Column Standardization",
		"description": "At the time of generating the event log, data records must share all the same columns, based on the activity being modelled. In order to ensure the uniformity of the final event log, this service is specified",
		"input": [ 
			{
				"name": "activity",
				"description": "The id or name of the activity whose schema will be taken as reference for the columns of the output CSV."
			},{
				"name": "fill",
				"description": "List of comma-separated values indicating those columns whose value for a data record, if empty, must be taken from the information collected by other sensors belonging to the same trace."
			}
		],
		"output": [ 
			{
				"name": "csv",
				"description": "Standardized CSV."
			}
		],
		"databases": ["Events"]
}

=== InnoTep/FGCS2022/Data structures/JSON/Team1/trace_behaviour_enrichment.json
{
		"name": "Trace Behaviour Enrichment",
		"description": "The trace behaviour enrichment service allows to extract new attributes that provide additional information about behavioural patterns of the originator associated with a trace of events. The output attribute’s values can differ along traces with the same originator, as they could include information regarding, for example, the overall mood of the patient during the execution of the activity.",
		"input": [ 
			{
				"name": "fields",
				"description": "List of comma-separated names of the columns with information about the originator."
			},{
				"name": "regex",
				"description": "List of comma-separated regular expressions to collect the information related to each attribute."
			},{
				"name": "trace_attrs",
				"description": "List of comma-separated names of the attributes’ columns. The number of elements of this parameter must coincide with the total sum of groups defined in the regular expressions specified before."
			},{
				"name": "trace_attr_types",
				"description": ": List of comma-separated values indicating the data type of each trace attribute. It is recommended that built-in JSON Schema or XML Schema data types are used, for example, string or number."
			}
		],
		"output": [ 
			{
				"name": "csv",
				"description": "CSV including the enriched information."
			}
		],
		"databases": ["Events"]
}

=== InnoTep/FGCS2022/Data structures/JSON/event_selection.json
{
	"name": "Event selection",
	"description": "Selects a subset of activities from the activity database",
	"input": [
		{"name": "collection_input",
		 "description": "Name of the collection that will be used to feed the service"},
		{"name": "start",
		 "description": "Timestamp indicating the beginning point from which events are selected"},
		{"name": "end",
		 "description": "Timestamp indicating the ending point until which events are selected"},
		{"name": "activity" ,
		 "description": "The name of the subtype or type of activity which wants to be selected"},
		{"name": "collection_output",
		 "description": "Name of the collection were the resulting records will be stored"}
	],
	"output": [
		{"name": "json",
		 "description": "JSON with the list of unique attributes identified accross activities"}
	],
	"databases": ["Activities", "Event_Log", "Schemas"]
}

=== InnoTep/FGCS2022/Data structures/JSON/Team1/trace_delimiter.json
{
		"name": "Trace Delimiter",
		"description": "In order to build an event log we must organize data in traces, which represent groups of events executed during the same activity. The trace delimiter services parses an input CSV and introduces a new column specifying the trace id for each event, based on the topic mask and the values for the start and finish events.",
		"input": [ 
			{
				"name": "mask",
				"description": "The topic mask to group same originator events."
			},{
				"name": "first",
				"description": "The data value indicating the start of a trace."
			},{
				"name": "last",
				"description": "The data value indicating the end of a trace"
			},{
				"name": "new",
				"description": "The name of the column with the trace id."
			}
		],
		"output": [ 
			{
				"name": "csv",
				"description": "Output CSV including the new column."
			}
		],
		"databases": ["Events"]
}
